<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit62a5350705101961f6e553a1c3990b30
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Component\\Translation\\' => 30,
        ),
        'J' => 
        array (
            'Jenssegers\\Date\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Component\\Translation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/translation',
        ),
        'Jenssegers\\Date\\' => 
        array (
            0 => __DIR__ . '/..' . '/jenssegers/date/src',
        ),
    );

    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/..' . '/nesbot/carbon/src',
    );

    public static $prefixesPsr0 = array (
        'U' => 
        array (
            'UpdateHelper\\' => 
            array (
                0 => __DIR__ . '/..' . '/kylekatarnls/update-helper/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit62a5350705101961f6e553a1c3990b30::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit62a5350705101961f6e553a1c3990b30::$prefixDirsPsr4;
            $loader->fallbackDirsPsr4 = ComposerStaticInit62a5350705101961f6e553a1c3990b30::$fallbackDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit62a5350705101961f6e553a1c3990b30::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
